pub(super) fn static_exact_match(name: &str, value: &[u8]) -> Option<usize> {
    static_name_indices(name).iter().copied().find(|index| {
        let (_, table_value) = STATIC_TABLE[*index];
        table_value.as_bytes() == value
    })
}

pub(super) fn static_name_index(name: &str) -> Option<usize> {
    static_name_indices(name).first().copied()
}

pub(super) fn static_field(index: usize) -> Option<(&'static str, &'static str)> {
    STATIC_TABLE.get(index).copied()
}

fn static_name_indices(name: &str) -> &'static [usize] {
    match name {
        ":authority" => &[0],
        ":path" => &[1],
        "age" => &[2],
        "content-disposition" => &[3],
        "content-length" => &[4],
        "cookie" => &[5],
        "date" => &[6],
        "etag" => &[7],
        "if-modified-since" => &[8],
        "if-none-match" => &[9],
        "last-modified" => &[10],
        "link" => &[11],
        "location" => &[12],
        "referer" => &[13],
        "set-cookie" => &[14],
        ":method" => &[15, 16, 17, 18, 19, 20, 21],
        ":scheme" => &[22, 23],
        ":status" => &[24, 25, 26, 27, 28, 63, 64, 65, 66, 67, 68, 69, 70],
        "accept" => &[29, 30],
        "accept-encoding" => &[31],
        "accept-ranges" => &[32],
        "access-control-allow-headers" => &[33, 34, 75],
        "access-control-allow-origin" => &[35],
        "cache-control" => &[36, 37, 38, 39, 40, 41],
        "content-encoding" => &[42, 43],
        "content-type" => &[44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
        "range" => &[55],
        "strict-transport-security" => &[56, 57, 58],
        "vary" => &[59, 60],
        "x-content-type-options" => &[61],
        "x-xss-protection" => &[62],
        "accept-language" => &[71],
        "access-control-allow-credentials" => &[72, 73],
        "access-control-allow-methods" => &[76, 77, 78],
        "access-control-expose-headers" => &[79],
        "access-control-request-headers" => &[80],
        "access-control-request-method" => &[81, 82],
        "alt-svc" => &[83],
        "authorization" => &[84],
        "content-security-policy" => &[85],
        "early-data" => &[86],
        "expect-ct" => &[87],
        "forwarded" => &[88],
        "if-range" => &[89],
        "origin" => &[90],
        "purpose" => &[91],
        "server" => &[92],
        "timing-allow-origin" => &[93],
        "upgrade-insecure-requests" => &[94],
        "user-agent" => &[95],
        "x-forwarded-for" => &[96],
        "x-frame-options" => &[97, 98],
        _ => &[],
    }
}

// QPACK static table from RFC 9204 Appendix A.
pub(super) const STATIC_TABLE: [(&str, &str); 99] = [
    (":authority", ""),
    (":path", "/"),
    ("age", "0"),
    ("content-disposition", ""),
    ("content-length", "0"),
    ("cookie", ""),
    ("date", ""),
    ("etag", ""),
    ("if-modified-since", ""),
    ("if-none-match", ""),
    ("last-modified", ""),
    ("link", ""),
    ("location", ""),
    ("referer", ""),
    ("set-cookie", ""),
    (":method", "CONNECT"),
    (":method", "DELETE"),
    (":method", "GET"),
    (":method", "HEAD"),
    (":method", "OPTIONS"),
    (":method", "POST"),
    (":method", "PUT"),
    (":scheme", "http"),
    (":scheme", "https"),
    (":status", "103"),
    (":status", "200"),
    (":status", "304"),
    (":status", "404"),
    (":status", "503"),
    ("accept", "*/*"),
    ("accept", "application/dns-message"),
    ("accept-encoding", "gzip, deflate, br"),
    ("accept-ranges", "bytes"),
    ("access-control-allow-headers", "cache-control"),
    ("access-control-allow-headers", "content-type"),
    ("access-control-allow-origin", "*"),
    ("cache-control", "max-age=0"),
    ("cache-control", "max-age=2592000"),
    ("cache-control", "max-age=604800"),
    ("cache-control", "no-cache"),
    ("cache-control", "no-store"),
    ("cache-control", "public, max-age=31536000"),
    ("content-encoding", "br"),
    ("content-encoding", "gzip"),
    ("content-type", "application/dns-message"),
    ("content-type", "application/javascript"),
    ("content-type", "application/json"),
    ("content-type", "application/x-www-form-urlencoded"),
    ("content-type", "image/gif"),
    ("content-type", "image/jpeg"),
    ("content-type", "image/png"),
    ("content-type", "text/css"),
    ("content-type", "text/html; charset=utf-8"),
    ("content-type", "text/plain"),
    ("content-type", "text/plain;charset=utf-8"),
    ("range", "bytes=0-"),
    ("strict-transport-security", "max-age=31536000"),
    (
        "strict-transport-security",
        "max-age=31536000; includesubdomains",
    ),
    (
        "strict-transport-security",
        "max-age=31536000; includesubdomains; preload",
    ),
    ("vary", "accept-encoding"),
    ("vary", "origin"),
    ("x-content-type-options", "nosniff"),
    ("x-xss-protection", "1; mode=block"),
    (":status", "100"),
    (":status", "204"),
    (":status", "206"),
    (":status", "302"),
    (":status", "400"),
    (":status", "403"),
    (":status", "421"),
    (":status", "425"),
    (":status", "500"),
    ("accept-language", ""),
    ("access-control-allow-credentials", "FALSE"),
    ("access-control-allow-credentials", "TRUE"),
    ("access-control-allow-headers", "*"),
    ("access-control-allow-methods", "get"),
    ("access-control-allow-methods", "get, post, options"),
    ("access-control-allow-methods", "options"),
    ("access-control-expose-headers", "content-length"),
    ("access-control-request-headers", "content-type"),
    ("access-control-request-method", "get"),
    ("access-control-request-method", "post"),
    ("alt-svc", "clear"),
    ("authorization", ""),
    (
        "content-security-policy",
        "script-src 'none'; object-src 'none'; base-uri 'none'",
    ),
    ("early-data", "1"),
    ("expect-ct", ""),
    ("forwarded", ""),
    ("if-range", ""),
    ("origin", ""),
    ("purpose", "prefetch"),
    ("server", ""),
    ("timing-allow-origin", "*"),
    ("upgrade-insecure-requests", "1"),
    ("user-agent", ""),
    ("x-forwarded-for", ""),
    ("x-frame-options", "deny"),
    ("x-frame-options", "sameorigin"),
];
