#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

require() {
  local file="$1"
  local needle="$2"
  if ! grep -Fq "$needle" "$file"; then
    echo "ci acceptance gate missing in ${file}: ${needle}" >&2
    exit 1
  fi
}

check_deny_skip_baseline() {
  local max_entries=53
  local entries
  entries="$(awk '
    $0 ~ /^skip = \[/ { in_skip = 1; next }
    in_skip && $0 ~ /^\]/ { in_skip = 0; next }
    in_skip && $0 ~ /^  \{ crate = / {
      entries += 1
      if ($0 !~ /reason = /) missing_reason += 1
    }
    END { printf "%d %d\n", entries, missing_reason }
  ' deny.toml)"
  local count missing_reason
  count="${entries%% *}"
  missing_reason="${entries##* }"
  if [ "$count" -gt "$max_entries" ]; then
    echo "deny.toml skip baseline exceeded: ${count} > ${max_entries}" >&2
    exit 1
  fi
  if [ "$missing_reason" -ne 0 ]; then
    echo "deny.toml skip entries missing reason: ${missing_reason}" >&2
    exit 1
  fi
}

require Cargo.toml 'rust-version = "1.92"'
require Cargo.toml 'dead_code = "deny"'
require Cargo.toml 'unused = "deny"'
require Cargo.toml 'unsafe_op_in_unsafe_fn = "deny"'
require Cargo.toml 'undocumented_unsafe_blocks = "deny"'
require qpx-acme/src/lib.rs '#![warn(missing_docs)]'
require qpx-auth/src/lib.rs '#![warn(missing_docs)]'
require qpx-auth/src/lib.rs '#![forbid(unsafe_code)]'
require qpx-h3/src/lib.rs '#![warn(missing_docs)]'
require qpx-h3/src/lib.rs '#![forbid(unsafe_code)]'
require qpx-h3/src/lib.rs 'pub enum H3Error'
require xtask/src/checks.rs 'pub trait method'
require xtask/src/checks.rs 'type_path_is_anyhow_result'
require xtask/src/checks.rs 'type_contains_anyhow_error'
require xtask/src/checks.rs 'pub struct field'
require xtask/src/checks.rs 'pub enum variant'
require xtask/src/checks.rs 'pub trait associated type'
require xtask/src/checks.rs 'collect_public_anyhow_items'
require xtask/src/checks.rs 'pub use'
require xtask/src/checks.rs 'pub async fn'
require xtask/src/checks.rs 'pub(crate) async fn'
require xtask/src/checks.rs 'check_workspace_lint_posture'
require xtask/src/checks.rs 'workspace lint posture violations'
require xtask/src/checks.rs 'check_dependency_policy_config'
require xtask/src/checks.rs 'dependency policy config violations'
require xtask/src/checks.rs 'DENY_SKIP_ENTRY_MAX'
require xtask/src/checks.rs 'RawMetricMacroVisitor'
require xtask/src/checks.rs 'join("tests")'
require xtask/src/checks.rs 'scan_duplicate_helpers_in_src'
require xtask/src/checks.rs 'DuplicateHelperScope::CfgTestOnly'
require xtask/src/checks.rs 'check_phase3_architecture_baselines'
require xtask/src/checks.rs 'DISPATCH_PARALLEL_FILE_BASELINES'
require xtask/src/checks.rs 'check_dispatch_access_commonality_baseline'
require xtask/src/checks.rs 'dispatch access commonality baseline exceeded'
require xtask/src/checks.rs 'check_dispatch_audit_builder_commonality'
require xtask/src/checks.rs 'dispatch audit builder commonality violations'
require xtask/src/checks.rs 'check_dispatch_cache_collapse_commonality'
require xtask/src/checks.rs 'dispatch cache collapse commonality baseline exceeded'
require xtask/src/checks.rs 'check_dispatch_limit_response_commonality'
require xtask/src/checks.rs 'dispatch limit response commonality baseline exceeded'
require xtask/src/checks.rs 'check_dispatch_annotated_local_response_commonality'
require xtask/src/checks.rs 'dispatch annotated local response commonality baseline exceeded'
require xtask/src/checks.rs 'check_dispatch_max_forwards_response_commonality'
require xtask/src/checks.rs 'dispatch max-forwards response commonality baseline exceeded'
require xtask/src/checks.rs 'check_dispatch_body_too_large_response_commonality'
require xtask/src/checks.rs 'dispatch body-too-large response commonality baseline exceeded'
require xtask/src/checks.rs 'check_response_capture_after_finalize'
require xtask/src/checks.rs 'response capture after-finalization violations'
require xtask/src/checks.rs 'check_proxy_authorization_header_boundary'
require xtask/src/checks.rs 'proxy authorization header boundary violations'
require xtask/src/checks.rs 'check_reverse_response_rules_dispatch_boundary'
require xtask/src/checks.rs 'reverse response rules dispatch boundary violations'
require xtask/src/checks.rs 'check_h3_origin_pool_load_semantics'
require xtask/src/checks.rs 'effective load must not double count open queue depth'
require xtask/src/checks.rs 'POOL_STRUCT_BASELINE_MAX'
require xtask/src/checks.rs 'QPXD_TLS_TYPE_BASELINE_MAX'
require xtask/src/checks.rs 'DIRECT_HEADER_MUTATION_BASELINE_MAX'
require xtask/src/checks.rs 'DIRECT_RESPONSE_POLICY_ENGINE_BASELINE_MAX'
require xtask/src/checks.rs 'count_direct_response_transform_files'
require xtask/src/checks.rs 'apply_response_headers('
require xtask/src/checks.rs 'check_canonical_config_loader_baseline'
require xtask/src/checks.rs 'canonical config loader baseline violations'
require xtask/src/checks.rs 'sample config guard must load qpx.example and qpxd usecases through the real loader'
require xtask/src/checks.rs 'check_manual_session_shard_modulo_baseline'
require xtask/src/checks.rs 'manual session shard modulo baseline exceeded'
require xtask/src/checks.rs 'check_shard_initialization_helper_baseline'
require xtask/src/checks.rs 'shard initialization helper baseline exceeded'
require xtask/src/checks.rs 'check_h3_open_queue_backpressure_baseline'
require xtask/src/checks.rs 'H3 origin open queue backpressure baseline exceeded'
require xtask/src/checks.rs 'request open uses sender mutex'
require xtask/src/checks.rs 'check_reverse_mirror_spawn_backpressure'
require xtask/src/checks.rs 'reverse mirror spawn backpressure baseline exceeded'
require xtask/src/checks.rs 'check_ext_authz_response_buffering'
require xtask/src/checks.rs 'ext_authz response buffering baseline exceeded'
require xtask/src/checks.rs 'check_reverse_retry_template_bounded_body'
require xtask/src/checks.rs 'reverse retry template bounded-body baseline exceeded'
require xtask/src/checks.rs 'check_qpxr_capture_publish_order'
require xtask/src/checks.rs 'qpxr capture publish order violations'
require xtask/src/checks.rs 'check_qpxf_ipc_cleanup_backpressure'
require xtask/src/checks.rs 'qpxf IPC cleanup/backpressure violations'
require xtask/src/checks.rs 'check_secure_file_write_boundaries'
require xtask/src/checks.rs 'secure file write boundary violations'
require xtask/src/checks.rs 'check_phase4_ci_acceptance_gates'
require xtask/src/checks.rs 'Phase 4 CI acceptance gate violations'
require xtask/src/checks.rs 'check_public_api_snapshot_script'
require xtask/src/checks.rs 'public API snapshot script violations'
require xtask/src/checks.rs 'check_security_qa_fuzz_targets'
require xtask/src/checks.rs 'security QA fuzz target violations'
require xtask/src/checks.rs 'PLAN_P3_FUZZ_TARGETS'
require xtask/src/checks.rs 'advisory structure LOC budget notices'
require xtask/src/checks.rs 'advisory workspace total LOC budget notices'
require xtask/src/checks.rs 'long function advisory count'
require qpx-observability/src/lib.rs '#![warn(missing_docs)]'
require qpx-wasm/src/lib.rs '#![warn(missing_docs)]'
require qpx-wasm/src/lib.rs '#![forbid(unsafe_code)]'
require qpxc/src/main.rs '#![forbid(unsafe_code)]'
require qpxd/src/policy_context/ext_authz.rs 'fn policy_id(&self) -> Option<&str>'
require qpxd/src/policy_context/ext_authz.rs 'fn policy_tags(&self) -> &[String]'
require qpxd/src/http/dispatch/audit_builder.rs 'build_dispatch_audit_context'
require qpxd/src/forward/request/dispatch.rs 'build_dispatch_audit_context'
require qpxd/src/forward/request/dispatch/policy.rs 'build_dispatch_audit_context'
require qpxd/src/http/mitm/dispatch.rs 'build_dispatch_audit_context'
require qpxd/src/transparent/http/dispatch/prepare_helpers.rs 'build_dispatch_audit_context'
require qpxd/src/http/dispatch/ext_authz_access.rs 'apply_ext_authz_http_access'
require qpxd/src/http/dispatch/access.rs 'apply_ext_authz_http_access'
require qpxd/src/reverse/transport/dispatch/access.rs 'apply_ext_authz_http_access'
require qpxd/src/reverse/transport/dispatch.rs 'annotated_max_forwards_response'
require qpxd/src/http/dispatch/prepare/response.rs 'request_body_too_large_response'
require qpxd/src/upstream/origin/http_backend/pool.rs 'typed_pool_slot'
require qpxd/src/upstream/origin/http_backend/pool.rs 'H2ConnectionReservation'
require qpxd/src/upstream/origin/http_backend/h3_pool.rs 'spawn_h3_request_open_actor'
require qpxd/src/upstream/origin/http_backend/h3_pool.rs 'send_h3_open_request'
require qpxd/src/upstream/origin/http_backend/h3_pool.rs 'open_queue_capacity'
require qpxd/src/upstream/origin/http_backend/h3_pool/pool.rs 'h3_connection_stream_capacity_for_limits'
require qpxd/src/upstream/origin/http_backend/h3_pool/pool.rs 'h3_connection_effective_load'
require qpxd/src/upstream/origin/http_backend/h3_pool/pool.rs 'h3_origin_saturated_wait_uses_effective_stream_capacity'
require qpxd/src/upstream/pool/mod.rs 'trait ConnectionPool<T>'
require qpxd/src/upstream/pool/cluster.rs 'impl ConnectionPool<ResolvedUpstreamProxy> for Arc<UpstreamProxyCluster>'
require qpxd/src/forward/h3/qpx/connect_upstream/pool.rs 'wait_for_inflight_below'
require qpxd/src/forward/h3/qpx/connect_upstream/pool.rs 'max_inflight_streams_per_session'
require qpxd/src/reverse/transport/mirrors.rs 'MIRROR_MAX_INFLIGHT_PER_ENDPOINT'
require qpxd/src/reverse/transport/mirrors.rs 'try_acquire_mirror_permit'
require qpxd/src/policy_context/ext_authz.rs 'EXT_AUTHZ_RESPONSE_BUFFERS'
require qpxd/src/policy_context/ext_authz.rs 'ExtAuthzBodyBuffer'
require qpxd/src/reverse/transport/request_template.rs 'content_length(req).is_some_and(|len| len <= body_threshold_bytes as u64)'
require qpx-core/src/config/validate/reverse.rs 'retry_body_threshold_bytes must be <= runtime.max_reverse_retry_template_body_bytes'
require qpxf/Cargo.toml 'memchr.workspace = true'
require qpxf/src/server/protocol.rs 'memchr::memmem'
require xtask/src/checks.rs 'check_qpxf_cgi_header_parser_zero_copy'
require qpxd/src/reverse/h3/streaming.rs 'request_side_fail_closed'
require qpxd/src/forward/h3/streaming.rs 'request_side_fail_closed'
require qpx-h3/src/transport/datagram.rs 'send_prefixed_datagram'
require qpx-h3/src/transport/datagram.rs 'send_unprefixed_datagram_with_scratch'
require qpx-h3/src/transport/datagram.rs 'ArcSwap<HashMap<u64, DatagramRoute>>'
require xtask/src/checks.rs 'qpx-h3 datagram send boundary violations'
require xtask/src/checks.rs 'ambiguous unprefixed send_datagram API'
require qpx-h3/src/sharding.rs 'modulo_u64'
require qpx-h3/src/client/registry.rs 'crate::sharding::modulo_u64'
require qpx-h3/src/server/registry.rs 'crate::sharding::modulo_u64'
require qpx-h3/src/transport/datagram.rs 'crate::sharding::modulo_u64'
require qpx-http/src/sharding.rs 'pub fn modulo_u64'
require qpx-http/src/sharding.rs 'pub fn sync_mutex_shards'
require qpx-http/src/sharding.rs 'pub fn async_mutex_shards'
require qpx-http/src/sharding.rs 'pub struct AsyncShardMap'
require qpxd/src/upstream/pool/sender_pool.rs 'AsyncShardMap'
require qpxd/src/ipc_client/pool.rs 'AsyncShardMap'
require qpxd/src/upstream/origin/http_backend/h3_pool/alt_svc.rs 'AsyncShardMap'
require qpxd/src/reverse/h3/passthrough/index/shared.rs 'qpx_http::sharding::modulo_u64'
require qpxd/src/transparent/udp/session/index.rs 'qpx_http::sharding::modulo_u64'
require qpxd/src/http/modules/response_compression/streaming.rs 'qpx_http::sharding::modulo_u64'
require qpx-core/src/secure_file.rs 'HardLinked'
require qpx-core/src/secure_file.rs 'validate_secure_file_handle'
require qpx-core/src/secure_file.rs 'file.set_permissions'
require qpx-core/src/tls/ca.rs 'validate_secure_file_handle'
require qpx-core/src/tls/ca.rs 'file.set_permissions'
require qpx-acme/src/provisioner.rs 'open_secure_output_file'
require qpx-acme/src/provisioner.rs 'file.set_permissions'
require qpx-core/src/shm_ring.rs 'validate_secure_shm_file(&file, path)?'
require qpx-core/src/shm_ring.rs 'file.set_permissions'
require qpxr/src/hub.rs 'qpx_core::secure_file::open_secure_output_file(path)'
require qpxr/src/hub.rs 'self.live_tx.send(encoded.clone())'
require qpxr/src/hub.rs 'tx.try_send(encoded)'
require qpxr/src/hub.rs 'fn duration_as_saturating_nanos'
require qpxr/src/hub.rs 'fn should_rotate_capture_file'
require qpxr/src/hub.rs 'checked_add(block_len)'
require qpx-core/src/tls/mod.rs 'pub use ca::{CaStore, load_or_generate_ca, write_ca_files}'
require qpx-core/src/tls/mod.rs 'pub use config::{build_client_config, build_server_config, load_cert_chain, load_private_key}'
require qpx-core/src/tls/mod.rs 'pub use resolver::{DynamicCertResolver, MitmConfig}'
require qpx-core/src/config/tests/sample_config_tests.rs 'fn sample_qpxd_configs_load'
require qpx-core/src/config/tests/sample_config_tests.rs 'expand_sample_env'
require docs/refactor-fwd-rev.md 'should not be fully merged'
require docs/refactor-fwd-rev.md 'the full forward/reverse request state machine'
require docs/refactor-crate-boundaries.md 'do not split qpxd solely to move LOC'
require docs/refactor-crate-boundaries.md 'no feature loss'
require docs/refactor-crate-boundaries.md 'Cargo-enforced dependency direction'
require xtask/src/checks.rs 'crate-boundary refactor documentation violations'
require qpx-core/src/tls/mod.rs 'mod trust'
require qpx-http/src/tls/mod.rs 'pub mod builder'
require qpx-http/src/tls/mod.rs 'pub mod client'
require qpx-http/src/tls/builder.rs 'qpx_core::tls::build_client_config'
require qpx-http/src/tls/builder.rs 'CompiledUpstreamTlsTrust::client_auth'
require qpxd/src/http/dispatch/response_policy.rs 'apply_dispatch_response_policy'
require qpxd/src/http/dispatch/response_policy.rs 'trait ResponseTransform'
require qpxd/src/http/dispatch/cache.rs 'dispatch_cache_collapse_continue'
require qpxd/src/http/dispatch/cache_decision.rs 'finalize_dispatch_collapsed_cache_decision'
require qpxd/src/reverse/transport/response_rules.rs 'fn response_policy_parts'
require qpxd/src/forward/h3/qpx/response.rs 'fn qpx_static_response'
require xtask/src/checks.rs 'check_qpx_h3_static_response_boundary'
require xtask/src/checks.rs 'check_rpc_frame_boundary_tests'
require qpxd/src/http/protocol/l7.rs 'finalize_response_headers_common'
require qpxd/src/http/protocol/l7.rs 'finalize_response_with_headers_in_place'
require qpxd/src/http/protocol/header_control.rs 'trait HeaderTransform'
require qpxd/src/http/protocol/header_control.rs 'set_proxy_authorization_header'
require deny.toml 'multiple-versions = "deny"'
require deny.toml 'wildcards = "allow"'
require xtask/src/checks.rs 'external_wildcard_dependency_violations'
require xtask/src/checks.rs 'must use workspace, path, or an explicit version'
require deny.toml 'skip-tree = []'
require deny.toml 'unknown-registry = "deny"'
require deny.toml 'unknown-git = "deny"'
require .github/workflows/ci.yml 'schedule:'
require .github/workflows/ci.yml "cron: '17 19 * * *'"
require .github/workflows/ci.yml 'dtolnay/rust-toolchain@1.92'
require .github/workflows/ci.yml 'cargo fmt --all -- --check'
require .github/workflows/ci.yml 'cargo check --workspace --locked'
require .github/workflows/ci.yml 'cargo build --workspace --all-targets --locked'
require .github/workflows/ci.yml 'cargo test --workspace --locked -- --test-threads=1'
require .github/workflows/ci.yml 'cargo doc --workspace --locked --no-deps --document-private-items'
require .github/workflows/ci.yml 'cargo llvm-cov --workspace --locked --fail-under-lines 20'
require .github/workflows/ci.yml 'bash ./scripts/check-public-api.sh'
require .github/workflows/ci.yml 'dtolnay/rust-toolchain@nightly'
require .github/workflows/ci.yml 'cargo clippy --workspace --all-targets --locked -- -D warnings'
require .github/workflows/ci.yml 'cargo clippy -p "${pkg}" --locked --all-targets --no-default-features --features "${features}" -- -D warnings'
require .github/workflows/ci.yml '"http3-backend-qpx"'
require .github/workflows/ci.yml '"http3-backend-h3,http3-backend-qpx,mitm,acme"'
require .github/workflows/ci.yml 'bnjbvr/cargo-machete@v0.6.0'
require .github/workflows/ci.yml 'cargo audit'
require .github/workflows/ci.yml 'cargo deny check'
require .github/workflows/ci.yml 'bash ./scripts/e2e-control-plane.sh'
require .github/workflows/ci.yml 'bash ./scripts/e2e-control-plane-soak.sh'
require .github/workflows/ci.yml 'bash ./scripts/e2e-config-samples.sh'
require .github/workflows/ci.yml 'bash ./scripts/e2e-local-response.sh'
require .github/workflows/ci.yml 'bash ./scripts/e2e-http2.sh'
require .github/workflows/ci.yml './scripts/e2e-control-plane.ps1'
require .github/workflows/ci.yml 'bash ./scripts/check-config-samples.sh'
require .github/workflows/ci.yml 'bash ./scripts/audit-config-usecases.sh'
require .github/workflows/ci.yml 'bash ./scripts/audit-config-behavior.sh'
require .github/workflows/ci.yml 'cargo test -p qpxd --release --test perf_smoke --locked -- --nocapture'
require .github/workflows/ci.yml 'cargo test -p qpxd --release --test advanced_transport_perf --locked -- --nocapture'
require .github/workflows/ci.yml "github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'"
require .github/workflows/ci.yml 'cargo bench -p qpxd --bench streaming_throughput --locked -- --sample-size 10'
require .github/workflows/security-qa.yml 'RUSTFLAGS: -Zsanitizer=address'
require .github/workflows/security-qa.yml 'cargo test -Zbuild-std --target x86_64-unknown-linux-gnu -p qpx-core --lib shm_ring --no-default-features --features ipc-support -- --nocapture'
require .github/workflows/security-qa.yml 'cargo test -Zbuild-std --target x86_64-unknown-linux-gnu -p qpxd ready_notifier_from_env_writes_readiness_byte -- --nocapture'
require .github/workflows/security-qa.yml 'cargo fuzz run "${target}"'
require .github/workflows/security-qa.yml 'config_canonical_loader'
require .github/workflows/security-qa.yml 'connect_frame_observer'
require .github/workflows/security-qa.yml 'datagram_capsule_parser'
require .github/workflows/security-qa.yml 'grpc_frame_observer'
require .github/workflows/security-qa.yml 'grpc_web_binary_frame_observer'
require .github/workflows/security-qa.yml 'grpc_web_text_base64_observer'
require .github/workflows/security-qa.yml 'reverse_target_input_deserializer'
require .github/workflows/security-qa.yml 'sse_event_observer'
require .github/workflows/security-qa.yml 'streaming_requirement_config_validator'
require .github/workflows/codeql.yml 'github/codeql-action/init@v4'
require .github/workflows/codeql.yml 'github/codeql-action/analyze@v4'
require .github/workflows/structure.yml 'bash ./scripts/check-ci-acceptance-gates.sh'
require .github/workflows/structure.yml 'cargo xtask structure'
require .github/workflows/structure.yml 'cargo xtask budget'
require scripts/check-public-api.sh 'check_crate qpx-core'
require scripts/check-public-api.sh 'check_crate qpx-auth'
require scripts/check-public-api.sh 'check_crate qpx-h3'
require scripts/check-public-api.sh 'check_crate qpx-acme'
require scripts/check-public-api.sh 'check_crate qpx-observability'
check_deny_skip_baseline
