state_dir: "${QPX_STATE_DIR:-~/.local/share/qpx}"
security:
  auth:
    users:
    - username: alice@example.invalid
      password: change-me
    - username: bob@example.invalid
      password: change-me
    - username: ops@example.invalid
      password: change-me
    - username: digestonly@example.invalid
      ha1: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
edges:
- kind: forward
  name: local-auth-forward
  listen: 127.0.0.1:18082
  default_action:
    type: block
  rules:
  - name: allow-authenticated-users
    match:
      host:
      - "*"
    auth:
      require:
      - local
    action:
      type: direct
