use std::net::IpAddr;

#[derive(Debug, Clone, Copy, Default)]
pub struct RuleMatchContext<'a> {
    pub src_ip: Option<IpAddr>,
    pub dst_port: Option<u16>,
    pub host: Option<&'a str>,
    pub sni: Option<&'a str>,
    pub method: Option<&'a str>,
    pub path: Option<&'a str>,
    pub query: Option<&'a str>,
    pub authority: Option<&'a str>,
    pub scheme: Option<&'a str>,
    pub http_version: Option<&'a str>,
    pub alpn: Option<&'a str>,
    pub tls_version: Option<&'a str>,
    pub destination_category: Option<&'a str>,
    pub destination_category_source: Option<&'a str>,
    pub destination_category_confidence: Option<u64>,
    pub destination_reputation: Option<&'a str>,
    pub destination_reputation_source: Option<&'a str>,
    pub destination_reputation_confidence: Option<u64>,
    pub destination_application: Option<&'a str>,
    pub destination_application_source: Option<&'a str>,
    pub destination_application_confidence: Option<u64>,
    pub ja3: Option<&'a str>,
    pub ja4: Option<&'a str>,
    pub request_size: Option<u64>,
    pub response_status: Option<u16>,
    pub response_size: Option<u64>,
    pub client_cert_present: Option<bool>,
    pub client_cert_subject: Option<&'a str>,
    pub client_cert_issuer: Option<&'a str>,
    pub client_cert_san_dns: &'a [String],
    pub client_cert_san_uri: &'a [String],
    pub client_cert_fingerprint_sha256: Option<&'a str>,
    pub upstream_cert_present: Option<bool>,
    pub upstream_cert_subject: Option<&'a str>,
    pub upstream_cert_issuer: Option<&'a str>,
    pub upstream_cert_san_dns: &'a [String],
    pub upstream_cert_san_uri: &'a [String],
    pub upstream_cert_fingerprint_sha256: Option<&'a str>,
    pub rpc_protocol: Option<&'a str>,
    pub rpc_service: Option<&'a str>,
    pub rpc_method: Option<&'a str>,
    pub rpc_streaming: Option<&'a str>,
    pub rpc_status: Option<&'a str>,
    pub rpc_message_size: Option<u64>,
    pub rpc_message: Option<&'a str>,
    pub rpc_trailers: Option<&'a http::HeaderMap>,
    pub headers: Option<&'a http::HeaderMap>,
    pub user: Option<&'a str>,
    pub user_groups: &'a [String],
    pub device_id: Option<&'a str>,
    pub posture: &'a [String],
    pub tenant: Option<&'a str>,
    pub auth_strength: Option<&'a str>,
    pub idp: Option<&'a str>,
}
